import { execSync } from 'child_process';

const OWNER = process.env.GITHUB_REPO_OWNER || 'sarallabs';
const REPO = process.env.GITHUB_REPO_NAME || 'saralvidhya-mvp';

// Automatically detect local git branch or default to 'abhi'
let localBranch = 'abhi';
try {
  localBranch = execSync('git rev-parse --abbrev-ref HEAD').toString().trim();
} catch (e) {
  // fallback
}
const TARGET_BRANCH = process.env.GITHUB_TARGET_BRANCH || localBranch;
const AUTO_PR = process.env.GITHUB_AUTO_PR === 'true';

// Helper for url encoding path segments safely
export function getSafeGitHubPath(filePath) {
  const parts = filePath.split('/');
  return parts.map(encodeURIComponent).join('/');
}

// Perform authenticated GitHub API fetch
async function githubFetch(endpoint, options = {}) {
  const token = process.env.GITHUB_PAT;
  if (!token) {
    throw new Error('GITHUB_PAT environment variable is not configured.');
  }

  const url = `https://api.github.com${endpoint}`;
  const headers = {
    'Authorization': `token ${token}`,
    'Accept': 'application/vnd.github.v3+json',
    'User-Agent': 'Ekam-Expert-Panel-API',
    ...options.headers
  };

  const response = await fetch(url, { ...options, headers });
  if (!response.ok) {
    let errMsg = `GitHub API Error: ${response.status} ${response.statusText}`;
    try {
      const errorData = await response.json();
      if (errorData.message) errMsg += ` (${errorData.message})`;
    } catch (e) {}
    throw new Error(errMsg);
  }
  return response;
}

// 1. Get SHA of a file (returns null if not found)
export async function getFileSHA(filePath, branch = TARGET_BRANCH) {
  const safePath = getSafeGitHubPath(filePath);
  try {
    const res = await githubFetch(`/repos/${OWNER}/${REPO}/contents/${safePath}?ref=${branch}`);
    const data = await res.json();
    return data.sha;
  } catch (err) {
    if (err.message.includes('404')) {
      return null;
    }
    throw err;
  }
}

// 2. Fetch file content from GitHub
export async function getGitHubFileContent(filePath, branch = TARGET_BRANCH) {
  const safePath = getSafeGitHubPath(filePath);
  const res = await githubFetch(`/repos/${OWNER}/${REPO}/contents/${safePath}?ref=${branch}`);
  const data = await res.json();
  
  if (data.encoding === 'base64') {
    // Decode base64 to utf-8 safely
    return Buffer.from(data.content, 'base64').toString('utf-8');
  }
  return data.content;
}

// 3. Commit/Save a file to GitHub
export async function commitGitHubFile(filePath, content, branch = TARGET_BRANCH, message = '') {
  const safePath = getSafeGitHubPath(filePath);
  const sha = await getFileSHA(filePath, branch);
  const base64Content = Buffer.from(content, 'utf-8').toString('base64');
  
  const commitMessage = message || `content(expert): update ${filePath.split('/').pop()}`;

  const body = {
    message: commitMessage,
    content: base64Content,
    branch
  };
  if (sha) {
    body.sha = sha;
  }

  const res = await githubFetch(`/repos/${OWNER}/${REPO}/contents/${safePath}`, {
    method: 'PUT',
    body: JSON.stringify(body),
    headers: { 'Content-Type': 'application/json' }
  });
  return res.json();
}

// 4. Create new branch from base branch
export async function createGitHubBranch(newBranchName, baseBranch = TARGET_BRANCH) {
  // Get base branch commit SHA
  const resRef = await githubFetch(`/repos/${OWNER}/${REPO}/git/ref/heads/${baseBranch}`);
  const refData = await resRef.json();
  const baseSHA = refData.object.sha;

  // Create new ref
  const resCreate = await githubFetch(`/repos/${OWNER}/${REPO}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({
      ref: `refs/heads/${newBranchName}`,
      sha: baseSHA
    }),
    headers: { 'Content-Type': 'application/json' }
  });
  return resCreate.json();
}

// 5. Create Pull Request
export async function createGitHubPR(title, headBranch, baseBranch = TARGET_BRANCH, body = '') {
  const res = await githubFetch(`/repos/${OWNER}/${REPO}/pulls`, {
    method: 'POST',
    body: JSON.stringify({
      title,
      head: headBranch,
      base: baseBranch,
      body: body || 'Automatically generated by Expert Panel.'
    }),
    headers: { 'Content-Type': 'application/json' }
  });
  return res.json();
}

// 6. Build the resource file tree from GitHub
export async function getGitHubResourceTree(branch = TARGET_BRANCH) {
  const res = await githubFetch(`/repos/${OWNER}/${REPO}/git/trees/${branch}?recursive=true`);
  const data = await res.json();
  
  const prefix = 'public/generated_resources/';
  const filteredFiles = data.tree
    .filter(item => item.path.startsWith(prefix) && item.path !== prefix)
    .map(item => ({
      path: item.path.substring(prefix.length),
      type: item.type === 'blob' ? 'file' : 'directory'
    }));

  return pathsToTree(filteredFiles);
}

// Helper to construct nested FileNode tree from path list
function pathsToTree(files) {
  const root = [];
  const map = {};

  // Sort files to process directories first or consistently
  files.sort((a, b) => a.path.localeCompare(b.path));

  for (const file of files) {
    const parts = file.path.split('/');
    let currentLevel = root;
    let currentPath = '';

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const isLast = i === parts.length - 1;

      if (!map[currentPath]) {
        const node = {
          name: part,
          path: currentPath,
          type: (isLast && file.type === 'file') ? 'file' : 'directory'
        };
        if (node.type === 'directory') {
          node.children = [];
        }
        map[currentPath] = node;
        currentLevel.push(node);
      }

      if (map[currentPath].type === 'directory') {
        currentLevel = map[currentPath].children;
      }
    }
  }
  return root;
}
