// Cloudflare Pages Functions Shared GitHub Helper
// This file is prefixed with an underscore so Cloudflare's router ignores it.

export function base64Encode(str) {
  return btoa(unescape(encodeURIComponent(str)));
}

export function base64Decode(str) {
  return decodeURIComponent(escape(atob(str)));
}

export function getSafeGitHubPath(filePath) {
  return filePath.split('/').map(encodeURIComponent).join('/');
}

// Perform authenticated GitHub API fetch
async function githubFetch(env, endpoint, options = {}) {
  const token = env.GITHUB_PAT;
  if (!token) {
    throw new Error('GITHUB_PAT environment variable is not configured on Cloudflare.');
  }

  const owner = env.GITHUB_REPO_OWNER || 'sarallabs';
  const repo = env.GITHUB_REPO_NAME || 'saralvidhya-mvp';
  const url = `https://api.github.com${endpoint}`;

  const headers = {
    'Authorization': `token ${token}`,
    'Accept': 'application/vnd.github.v3+json',
    'User-Agent': 'Ekam-Expert-Panel-Cloudflare-Worker',
    ...options.headers
  };

  const response = await fetch(url, { ...options, headers });
  if (!response.ok) {
    let errMsg = `GitHub API Error: ${response.status} ${response.statusText}`;
    try {
      const errorData = await response.json();
      if (errorData.message) errMsg += ` (${errorData.message})`;
    } catch (e) {}
    throw new Error(errMsg);
  }
  return response;
}

// 1. Get SHA of a file (returns null if not found)
export async function getFileSHA(env, filePath, branch) {
  const safePath = getSafeGitHubPath(filePath);
  const owner = env.GITHUB_REPO_OWNER || 'sarallabs';
  const repo = env.GITHUB_REPO_NAME || 'saralvidhya-mvp';
  try {
    const res = await githubFetch(env, `/repos/${owner}/${repo}/contents/${safePath}?ref=${branch}`);
    const data = await res.json();
    return data.sha;
  } catch (err) {
    if (err.message.includes('404')) {
      return null;
    }
    throw err;
  }
}

// 2. Fetch file content from GitHub
export async function getGitHubFileContent(env, filePath, branch) {
  const safePath = getSafeGitHubPath(filePath);
  const owner = env.GITHUB_REPO_OWNER || 'sarallabs';
  const repo = env.GITHUB_REPO_NAME || 'saralvidhya-mvp';
  const res = await githubFetch(env, `/repos/${owner}/${repo}/contents/${safePath}?ref=${branch}`);
  const data = await res.json();
  
  if (data.encoding === 'base64') {
    // Decode base64 to utf-8 safely
    return base64Decode(data.content.replace(/\s/g, ''));
  }
  return data.content;
}

// 3. Commit/Save a file to GitHub
export async function commitGitHubFile(env, filePath, content, branch, message = '') {
  const safePath = getSafeGitHubPath(filePath);
  const sha = await getFileSHA(env, filePath, branch);
  const base64Content = base64Encode(content);
  const owner = env.GITHUB_REPO_OWNER || 'sarallabs';
  const repo = env.GITHUB_REPO_NAME || 'saralvidhya-mvp';
  
  const commitMessage = message || `content(expert): update ${filePath.split('/').pop()}`;

  const body = {
    message: commitMessage,
    content: base64Content,
    branch
  };
  if (sha) {
    body.sha = sha;
  }

  const res = await githubFetch(env, `/repos/${owner}/${repo}/contents/${safePath}`, {
    method: 'PUT',
    body: JSON.stringify(body),
    headers: { 'Content-Type': 'application/json' }
  });
  return res.json();
}

// 4. Create new branch from base branch
export async function createGitHubBranch(env, newBranchName, baseBranch) {
  const owner = env.GITHUB_REPO_OWNER || 'sarallabs';
  const repo = env.GITHUB_REPO_NAME || 'saralvidhya-mvp';

  // Get base branch commit SHA
  const resRef = await githubFetch(env, `/repos/${owner}/${repo}/git/ref/heads/${baseBranch}`);
  const refData = await resRef.json();
  const baseSHA = refData.object.sha;

  // Create new ref
  const resCreate = await githubFetch(env, `/repos/${owner}/${repo}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({
      ref: `refs/heads/${newBranchName}`,
      sha: baseSHA
    }),
    headers: { 'Content-Type': 'application/json' }
  });
  return resCreate.json();
}

// 5. Create Pull Request
export async function createGitHubPR(env, title, headBranch, baseBranch, body = '') {
  const owner = env.GITHUB_REPO_OWNER || 'sarallabs';
  const repo = env.GITHUB_REPO_NAME || 'saralvidhya-mvp';

  const res = await githubFetch(env, `/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    body: JSON.stringify({
      title,
      head: headBranch,
      base: baseBranch,
      body: body || 'Automatically generated by Expert Panel.'
    }),
    headers: { 'Content-Type': 'application/json' }
  });
  return res.json();
}

// 6. Build the resource file tree from GitHub
export async function getGitHubResourceTree(env, branch) {
  const owner = env.GITHUB_REPO_OWNER || 'sarallabs';
  const repo = env.GITHUB_REPO_NAME || 'saralvidhya-mvp';

  const res = await githubFetch(env, `/repos/${owner}/${repo}/git/trees/${branch}?recursive=true`);
  const data = await res.json();
  
  const prefix = 'public/generated_resources/';
  const filteredFiles = data.tree
    .filter(item => item.path.startsWith(prefix) && item.path !== prefix)
    .map(item => ({
      path: item.path.substring(prefix.length),
      type: item.type === 'blob' ? 'file' : 'directory'
    }));

  return pathsToTree(filteredFiles);
}

// Helper to construct nested FileNode tree from path list
function pathsToTree(files) {
  const root = [];
  const map = {};

  files.sort((a, b) => a.path.localeCompare(b.path));

  for (const file of files) {
    const parts = file.path.split('/');
    let currentLevel = root;
    let currentPath = '';

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const isLast = i === parts.length - 1;

      if (!map[currentPath]) {
        const node = {
          name: part,
          path: currentPath,
          type: (isLast && file.type === 'file') ? 'file' : 'directory'
        };
        if (node.type === 'directory') {
          node.children = [];
        }
        map[currentPath] = node;
        currentLevel.push(node);
      }

      if (map[currentPath].type === 'directory') {
        currentLevel = map[currentPath].children;
      }
    }
  }
  return root;
}

// CORS Headers helper for Cloudflare responses
export function corsHeaders() {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, PUT, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    'Content-Type': 'application/json'
  };
}
