const fs = require('fs');
const path = require('path');

const ch3JsonPath = path.resolve('public/generated_resources/angrau/chapter_03/question_bank.json');
const ch3PracticeJsonPath = path.resolve('public/generated_resources/angrau/chapter_03/Practice/Question Bank/question_bank.json');
const prodCh3Path = path.resolve('../saralvidhya-production/content/angrau/entomology/chapter_03/practice/question_bank.json');

const rubric = {
  pillar_1_nomenclature: "1.5 Marks",
  pillar_2_mechanisms_and_kinetics: "3.5 Marks",
  pillar_3_comparative_matrix: "2.0 Marks",
  pillar_4_agronomic_applications: "2.0 Marks",
  pillar_5_diagnostic_synthesis: "1.0 Mark",
  total_marks: "10.0 Marks"
};

const answers10M = {
  QB_WTH_05_001: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Weathering (*sensu stricto*) is defined as the *in situ* mechanical disintegration and biochemical decomposition of rocks, mineral aggregates, and pedogenic precursors exposed at or near the Earth's lithospheric surface under atmospheric, hydrospheric, and biotic influences. The process is uniquely Janus-faced in geological and soil science: it operates simultaneously as a destructive breakdown mechanism and as an essential constructive (synthetic) geochemical factory.",
    pillar_2_mechanisms_and_kinetics: "1. Destructive Phase: High-temperature, high-pressure end-member primary minerals crystallised under deep magmatic or metamorphic conditions (e.g., Olivine, Augite, Hornblende, Anorthite) are thermodynamically unstable at 1 atm and 25°C. Atmospheric moisture, dissolved CO2 (forming carbonic acid H2CO3), and biogenic exudates cleave covalent Si-O-Si bonds and coordinate metal cations (Ca2+, Mg2+, Fe2+, K+, Na+) through hydrolysis, oxidation, and proton attack.\n2. Synthetic / Constructive Phase: Dissolved silicon (H4SiO4), aluminium (Al3+ / Al(OH)2+), and structural cations re-precipitate into thermodynamically stable, low-temperature secondary crystalline clay minerals (smectite, illite, kaolinite) and sesquioxides (hematite Fe2O3, goethite FeOOH, gibbsite Al(OH)3). Carbonates (calcite CaCO3) and gypsum precipitate within pedogenic calcic horizons.\n3. Equilibrium Kinetics: Thermodynamic dissolution follows Goldich's Dissolution Series, while synthesis is governed by chemical activity ratios (e.g., [H4SiO4] vs [Al3+]/[H+]3), dictating whether 2:1 expansive smectite or 1:1 non-expansive kaolinite crystallises.",
    pillar_3_comparative_matrix: "| Parameter | Destructive Weathering Phase | Synthetic (Constructive) Weathering Phase |\n| :--- | :--- | :--- |\n| **Thermodynamic Direction** | Entropy-driven lattice collapse of high-temp primary silicates | Enthalpy-favoured crystallization of secondary pedogenic minerals |\n| **Starting Precursors** | Olivine, Pyroxenes, Feldspars, Micas, Amphiboles | Solvated ions: H4SiO4, Al(OH)4^-, Fe3+, Ca2+, Mg2+, K+ |\n| **End Products** | Amorphous gels, dissolved cations, fragmented skeletal clasts | Layer phyllosilicates (kaolinite, smectite), sesquioxides (goethite) |\n| **Physical Impact** | Commutation, loss of rock cohesion, porosity expansion | Clay flocculation, cementation, ped formation, structure building |\n| **Agronomic Role** | Releases trapped base cations into labile soil solutions | Creates Cation Exchange Capacity (CEC) and nutrient sorption matrix |",
    pillar_4_agronomic_applications: "1. Genesis of Cation Exchange Capacity (CEC): Without secondary clay synthesis, soils would remain sterile sand/gravel deposits devoid of charge. Secondary phyllosilicates provide isomorphic substitution charges (CEC 10–100 cmol(+)/kg), retaining NH4+, K+, Ca2+, and Mg2+ against monsoonal leaching.\n2. Micronutrient Solubilization & Fertilizer Retention: Primary mineral destruction liberates trace minerals (Fe, Mn, Zn, Cu, B, Mo) necessary for enzymatic catalysis in crops. The synthesized secondary iron oxides buffer phosphorus fixation dynamics in red and lateritic soils (Alfisols/Ultisols).\n3. Structural Aggregate Stability: Synthesized clay-humus colloidal complexes aggregate coarse mineral grains into granular and blocky peds, optimizing hydraulic conductivity, aeration, and plant root penetration.",
    pillar_5_diagnostic_synthesis: "[PRIMARY ROCK & SILICATE BEDROCK]\n               |\n               v  (Destructive: Hydrolysis, Oxidation, Cryofracture)\n[SOLVATED IONS (H4SiO4, Al3+, Ca2+, Mg2+, K+) + SKELETAL QUARTZ RESIDUE]\n               |\n               v  (Synthetic: Polymerization, Neo-crystallization)\n[SECONDARY PHYLLOSILICATE CLAYS (Kaolinite, Smectite) & SESQUIOXIDES (FeOOH)]\n               |\n               +--> Adsorption of Biogenic Humus & Colonization\n               v\n[TRUE FERTILE AGRICULTURAL SOLUM (A + B Horizons with High CEC & Water Capacity)]"
  },

  QB_WTH_05_002: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Regolith (from Greek *rhegos* = blanket, *lithos* = stone) represents the entire unconsolidated, heterogeneous mantle of fragmented bedrock debris, weathered saprolite, and allochthonous sediment resting above unaltered crystalline parent bedrock (the R horizon). In sharp contrast, the Solum (Latin for 'soil' or 'ground') comprises exclusively the upper, genetically differentiated master horizons (A, E, and B) that have undergone pedochemical organisation, biological humification, and structural pedal differentiation.",
    pillar_2_mechanisms_and_kinetics: "1. Pedogenetic Differentiation: The transformation of raw, sterile regolith into a solum requires biogeochemical inputs: humification of vegetative residues, melanisation of the epipedon, eluviation of mobile colloids (E horizon), and illuvial accumulation of secondary silicate clays, iron-aluminium oxides, or carbonates in the endopedon (B horizon).\n2. Boundary Demarcation: The lower boundary of the solum is the transition into the C horizon (the unconsolidated, little-altered regolith devoid of pedogenic structure), which in turn overlies the basal weathering front (saprock and unweathered R bedrock).\n3. Energy & Chemical Dynamics: In regolith, weathering is dominated by abiotic geochemistry (abiotic hydrolysis, hydration, physical shatter); in the solum, enzymatic organic decomposition, carbonic acid respiration (microbial pCO2 up to 10–100× atmospheric), and root organic chelation dominate kinetics.",
    pillar_3_comparative_matrix: "| Morphological Attribute | Regolith (Weathered Mantle / C-Horizon) | True Agricultural Soil (Solum: A + B Horizons) |\n| :--- | :--- | :--- |\n| **Vertical Stratigraphy** | Extends from solum base to unweathered parent bedrock | Confined to uppermost A, E, and B genetic horizons |\n| **Organic Matter Content** | Extremely low (<0.1%), lacking humified organic fractions | Abundant (0.5%–5.0%+), rich in humic/fulvic acid networks |\n| **Pedological Structure** | Massive, structureless, or relict rock fabric (saprolite) | Well-differentiated peds (granular, subangular blocky, prismatic) |\n| **Microbial / Faunal Density** | Minimal microbiological populations, largely oligotrophic | Hyper-diverse microbiome (bacteria, mycorrhizae, nematodes) |\n| **Agronomic Productivity** | Incapable of sustaining economic crops (suffocation/starvation) | Optimal root anchoring, water retention, and bio-available nutrients |",
    pillar_4_agronomic_applications: "1. Diagnostic Rooting Zone Delimitation: Crop rooting depth, tillage depth, and fertilizer placement depend entirely on solum thickness. In shallow Entisols/Inceptisols where solum depth <20 cm, root restriction induces drought vulnerability.\n2. Drainage & Saprolite Water Storage: In deep Alfisols and Vertisols, understanding the underlying C-horizon regolith allows hydrologists to predict perched water tables and seasonal capillary rise into the crop root zone.\n3. Land Capability Classification (LCC): The depth of true solum vs regolith dictates class assignment (e.g., Class I arable vs Class VI non-arable grazing land).",
    pillar_5_diagnostic_synthesis: "[SURFACE CANOPY & CROP BIOMASS]\n              |\n  ============== [O Horizon: Fresh & Decomposing Organic Detritus] ==============\n  ============== [A Horizon: Mineral Layer Melanized by Humus; Topsoil] ===========\n    SOLUM        [E Horizon: Eluviated Bleached Zone of Leaching]             |\n  (A + E + B)    [B Horizon: Illuvial Accumulation of Clays & Sesquioxides]   | REGOLITH\n  ============== [Solum-Regolith Boundary: Disappearance of Ped Structure] =======| (Entire\n                 [C Horizon: Saprolite, Weathered Rock Debris; Little Soil Action] | Unconsolidated\n                 =================================================================| Mantle)\n                 [R Layer: Massive, Impermeable Unweathered Crystalline Bedrock]"
  },

  QB_WTH_05_003: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Weathering phenomena are categorised into three universal, concurrent processes based on driving energy vectors: Physical (Mechanical) Weathering, which fragments rock masses without chemical alteration; Chemical Weathering (Decomposition), which alters molecular mineral crystal lattices; and Biological Weathering, which deploys living organisms exerting combined biophysical forces and biochemical metabolic secretions.",
    pillar_2_mechanisms_and_kinetics: "1. Physical Weathering: Driven by stress mechanics (thermal coefficient differentials ΔV = V0·β·ΔT, ice volumetric expansion ΔV = +9.05% yielding up to 210 MPa hydrostatic pressure, salt crystallization pressures, and overburden release exfoliation). Zero chemical bonds are broken except along mechanical cleavage planes.\n2. Chemical Weathering: Driven by thermodynamics (hydration of anhydrite to gypsum, carbonation H2O + CO2 ⇌ H2CO3, silicate hydrolysis, oxidation of Fe2+ to Fe3+). Primary mineral lattices dissolve, liberating mobile cations and neo-forming clays.\n3. Biological Weathering: Driven by root hydrostatic turgor pressure (generating mechanical turgor up to 1.5–2.0 MPa within fissures) and biogenic chemical reagents (rhizosphere carbonic acid, oxalic and citric acids chelating Fe3+ and Al3+, and lichen lichenic acids).",
    pillar_3_comparative_matrix: "| Parameter | Physical Weathering | Chemical Weathering | Biological Weathering |\n| :--- | :--- | :--- | :--- |\n| **Primary Mechanism** | Mechanical stress, tensile & shear failure | Lattice reaction, hydrolysis, redox, solution | Root wedging, burrowing + organic acid chelation |\n| **Chemical Composition** | Strictly preserved; identical to parent rock | Substantially altered; new phases synthesized | Highly altered in rhizosphere; enriched in bio-organics |\n| **Dominant Climatology** | Arid deserts, periglacial alpine zones | Warm, humid tropical & subtropical climates | Humid temperate to tropical vegetated biomes |\n| **Primary End Products** | Angular clasts, scree, coarse sand particles | Hydrous secondary clays, oxides, solutes | Micro-porous saprolite, organo-mineral complexes |\n| **Speed of Action** | Episodic, triggered by temperature/freeze | Continuous, moisture- and temp-dependent | Synergistic, tied to plant growth & microbial bloom |",
    pillar_4_agronomic_applications: "1. Topographic Soil Profile Development: Physical weathering dominates arid zone entisols; chemical weathering creates deep oxic and argillic horizons in tropical soils; biological weathering drives fertile mollisol formation under grasslands.\n2. Rock Phosphate Solubilization: Bio-weathering mechanisms are utilized directly in agriculture via Phosphate Solubilizing Bacteria (PSB, *Pseudomonas striata*, *Bacillus megaterium*) producing gluconic acid to dissolve insoluble rock phosphate.\n3. Agricultural Sand Texture Conditioning: Physical disintegration of quartz rocks establishes the drainage, aerating sand fraction essential for root vegetables (potato, groundnut).",
    pillar_5_diagnostic_synthesis: "                       [MASSIVE PARENT ROCK]\n                                  |\n       +--------------------------+--------------------------+\n       |                          |                          |\n       v                          v                          v\n[PHYSICAL FORCES]        [CHEMICAL REAGENTS]        [BIOLOGICAL AGENTS]\n• Thermal Expansion       • Hydrolysis (H+ Attack)   • Root Hydraulic Wedging\n• Frost Ice Wedging       • Carbonation (H2CO3)      • Microbial Organic Acids\n• Salt Crystallization    • Oxidation (Fe2+->Fe3+)   • Earthworm/Faunal Pedoturbation\n       |                          |                          |\n       +--------------------------+--------------------------+\n                                  |\n                                  v\n          [EXPONENTIALLY ACCELERATED SOIL FORMATION MATRIX]"
  },

  QB_WTH_05_004: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "The disintegration and decomposition of lithospheric materials proceed through a synergistic positive feedback loop wherein physical comminution and chemical lattice transformation mutually accelerate each other. Physical fragmentation converts massive, low-surface-area rock bodies into billions of microscopic particles, exponentially expanding reactive surface area; simultaneously, chemical weathering corrodes mineral cements and crystal grain boundaries, degrading tensile strength and preconditioning rocks for mechanical fracturing.",
    pillar_2_mechanisms_and_kinetics: "1. Surface Area Amplification (Physical -> Chemical): The rate of heterogeneous solid-liquid chemical reactions is directly proportional to specific surface area (m2/g). If a 1 cm3 cubic rock (surface area = 6 cm2) is comminuted into clay-sized cubes of 1 μm edge length, the total surface area expands 10,000-fold to 60,000 cm2 (6 m2), increasing reaction sites by four orders of magnitude.\n2. Structural Degradation (Chemical -> Physical): Hydrolysis and hydration selectively dissolve mineral grain boundaries (e.g., plagioclase in granite). As feldspars alter into soft, hydrated kaolinite (Mohs hardness 2 vs 6), rock tensile strength drops from >100 MPa to <5 MPa, allowing minimal thermal stress or root expansion to shatter the remaining rock matrix.\n3. Permeability Infiltration: Chemical leaching removes soluble calcite or silica cements in sandstones, generating macro-pores and micro-fissures that allow frost wedging and water percolation deep into the rock core.",
    pillar_3_comparative_matrix: "| Feedback Component | Physical Impact on Chemical Phase | Chemical Impact on Physical Phase |\n| :--- | :--- | :--- |\n| **Geometric Influence** | Exponentially multiplies specific surface area ($A/V$) | Forms micro-voids, etching pits, and porosity networks |\n| **Energy & Kinetics** | Exposes fresh unweathered mineral cleavage planes | Lowers activation energy for mechanical fracture propagation |\n| **Mechanical Cohesion** | Increases exposure to atmospheric moisture & gases | Destroys interlocking crystal fabrics & cements |\n| **Rate Relationship** | Linear physical comminution -> Exponential chemical rate | Subtle chemical rotting -> Catastrophic physical collapse |\n| **Field Manifestation**| Rapid weathering of glacier rock flour vs massive rock | Exfoliation shells peeling from chemically rotted cores |",
    pillar_4_agronomic_applications: "1. Agronomic Tillage Optimization: Mechanical cultivation (ploughing, harrowing) shatters soil clods, mirroring physical weathering to expose fresh mineral surfaces for chemical ion exchange and fertilizer dissolution.\n2. Powdered Mineral Fertilization: Applying rock dust (e.g., basalt powder, rock phosphate) requires fine grinding (<100 mesh) to activate the physical-chemical feedback, ensuring rapid soil remineralization and CO2 sequestration.\n3. Soil Salinity & Gypsum Weathering: Fine crushing of agricultural gypsum (CaSO4·2H2O) drastically accelerates its chemical dissolution in sodic soil reclamation.",
    pillar_5_diagnostic_synthesis: "       [PHYSICAL MECHANICAL FORCES (Cryofracture, Thermal, Abrasion)]\n                                  |\n                                  v\n     [Expands Specific Surface Area & Opens Internal Micro-Fissures]\n                                  |\n                                  v\n       [CHEMICAL DECOMPOSITION (Hydrolysis, Oxidation, Carbonation)]\n                                  |\n                                  v\n      [Dissolves Mineral Grain Boundaries & Degrades Tensile Strength]\n                                  |\n                                  v\n   [ROCK HIGHLY VULNERABLE: CATASTROPHIC STRUCTURAL BREAKDOWN ACCELERATES]"
  },

  QB_WTH_05_005: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Rock permeability—the physical property quantifying a porous medium's intrinsic capacity to transmit fluids through interconnected void networks under hydraulic or capillary gradients—is the foremost lithological governor of internal weathering rates. While rock mineralogy establishes thermodynamic vulnerability, permeability dictates whether the essential reactive agents (liquid water, solvated carbonic acid, atmospheric oxygen, and biogenic chelates) can penetrate beyond the superficial exterior into the internal rock fabric.",
    pillar_2_mechanisms_and_kinetics: "1. Darcy Fluid Transmission: Permeability ($k$, measured in Darcy or m2) controls convective and advective fluid flux ($q = -\\frac{k}{\\mu} \\nabla P$). Highly permeable lithologies permit deep, rapid advection of unsaturated meteoric rainwater, maintaining high chemical affinity and displacing saturated, equilibrium boundary layers.\n2. Internal Dissolved Gas Supply: Deep weathering requires continuous flux of atmospheric O2 (for oxidising Fe(II) silicates) and CO2 (generating H2CO3). In dense, impermeable rocks, dissolved oxygen is depleted within millimetres of the surface; in permeable strata, oxic weathering fronts extend tens of metres.\n3. Capillary Retention & Chemical Dwell Time: Micro-pore networks sustain capillary water films during seasonal droughts, enabling continuous hydrolysis and dissolution even in rainless months.\n4. Hydraulic Frost Shattering: In rocks with interconnected porosity, water saturation allows frost expansion (+9.05% by volume) to exert confined tensile stresses up to 210 MPa, shattering rock from within.",
    pillar_3_comparative_matrix: "| Lithological Class | Permeability ($k$) Range | Internal Weathering Regime | Weathering Front Profile |\n| :--- | :--- | :--- | :--- |\n| **Porous Clastic Sandstone** | High ($10^{-13}$ to $10^{-11} \\text{ m}^2$) | Pervasive, 3-dimensional internal leaching | Deep, diffuse, multi-meter saprolite layer |\n| **Fissured Basalt Flow** | Moderate ($10^{-15}$ to $10^{-13} \\text{ m}^2$) | Joint-guided internal spheroidal decomposition | Stepped, block-confined weathering rinds |\n| **Massive Granite Pluton** | Low/Negligible ($<10^{-18} \\text{ m}^2$) | Strictly planar, skin-deep exfoliation | Sharp, shallow interface; fresh unweathered core |\n| **Unfractured Slate/Shale** | Impermeable across beds | Surface runoff dominated; internal freeze proof | Confined to parallel fissility cleavage planes |",
    pillar_4_agronomic_applications: "1. Soil Parent Material Depth Prediction: Highly permeable parent rocks yield deep agricultural soils (deep sandy loams and loamy sands) ideal for tap-rooted perennial orchards and tree crops.\n2. Groundwater Aquifer Recharge in Agricultural Basins: Weathered permeable parent rocks act as major unconfined aquifers supplying agricultural irrigation borewells throughout semi-arid river basins.\n3. Subsoil Drainage & Salinity Hazard: Impermeable bedrock underlying agricultural land creates perched water tables, driving secondary salinization in canal command areas.",
    pillar_5_diagnostic_synthesis: "                     [METEORIC PRECIPITATION (H2O + CO2 + O2)]\n                                        |\n            +---------------------------+---------------------------+\n            |                                                       |\n            v                                                       v\n[HIGH PERMEABILITY (Porous Sandstone)]            [LOW PERMEABILITY (Massive Granite)]\n• Convective Fluid Infiltration                   • Surface Runoff Dominated (>95%)\n• Continuous Dissolved Gas Supply                 • Fluid Entry Blocked at Perimeter\n• Internal Capillary Water Films Retained         • Zero Internal Hydrolysis / Cryofracture\n• Frost Wedging Within Pores                      • Weathering Restricted to 1mm 'Skin'\n            |                                                       |\n            v                                                       v\n[DEEP 3-DIMENSIONAL SAPROLITE GENESIS]             [SUPERFICIAL WEATHERING RINDS ONLY]"
  },

  QB_WTH_05_006: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "The weathering velocity hierarchy under subaerial weathering conditions adheres strictly to the sequence: **Porous Sandstone > Dense Basalt > Massive Granite**. This differential weathering velocity is dictated by the interaction of petrographic texture, primary mineral thermodynamic stability (Goldich's Dissolution Series), porosity-permeability networks, and rock crystalline coherence.",
    pillar_2_mechanisms_and_kinetics: "1. Porous Sandstone (Highest Velocity): Formed of clastic quartz and feldspar grains bound by chemical cements (calcite CaCO3, iron oxides, or silica). Its high effective porosity (15–30%) allows rapid water ingress. Calcite cement dissolves rapidly via carbonation (CaCO3 + H2CO3 ⇌ Ca(HCO3)2), causing sand grains to disaggregate mechanically.\n2. Dense Basalt (Intermediate Velocity): Extrusive mafic igneous rock consisting of fine-grained plagioclase (labradorite) and ferromagnesian minerals (augite, olivine). Basalt exhibits high chemical vulnerability due to abundant Fe(II) and Mg(II) silicates at the top of Goldich's series, but its dense, aphanitic texture limits weathering to cooling columnar joints and vesicle networks.\n3. Massive Granite (Lowest Velocity): Plutonic felsic rock characterized by a coarse, interlocking crystalline fabric composed predominantly of quartz (30%), orthoclase feldspar (40%), and minor biotite. Quartz is thermodynamically inert at surface conditions; low primary porosity (<1%) shields the rock from internal fluid penetration.",
    pillar_3_comparative_matrix: "| Parameter | Porous Sandstone | Dense Basalt | Massive Granite |\n| :--- | :--- | :--- | :--- |\n| **Petrological Origin** | Clastic Sedimentary | Extrusive Mafic Igneous | Intrusive Felsic Plutonic |\n| **Dominant Mineralogy** | Quartz grains + Calcite/Clay cement | Plagioclase + Augite + Olivine | Quartz + K-Feldspar + Biotite |\n| **Thermodynamic Stability**| Low (due to soluble cement bond) | Very Low (olivine/pyroxene) | Extremely High (quartz & microcline) |\n| **Internal Porosity** | 15%–30% (High interconnected pores) | 1%–5% (Joints & vesicles only) | <1% (Microscopic grain boundary microfractures) |\n| **Weathering Mechanism** | Grain disaggregation & cement leaching | Spheroidal weathering & oxidation | Exfoliation spalling & grusification |\n| **Resulting Soil Type** | Sandy, light-textured Entisols/Inceptisols | Heavy, nutrient-rich Black Vertisols | Red sandy-clay Alfisols/Ultisols |",
    pillar_4_agronomic_applications: "1. Soil Texture & Fertility Forecasting: Basalt terrains weather into fertile, montmorillonite-rich Vertisols (Black Cotton Soils) with high CEC; granite weathers into well-drained, kaolinitic Red Alfisols requiring potassium and phosphorus management.\n2. Agricultural Quarrying & Terracing Materials: Granite provides durable materials for agricultural check-dams, drainage retaining walls, and bunds, whereas sandstone rapidly disintegrates under hydrostatic water pressure.\n3. Agricultural Water Supply: Sandstone formations act as excellent primary aquifers; basalt provides fractured-rock water tables; unjointed massive granite yields dry unproductive drill-holes.",
    pillar_5_diagnostic_synthesis: "                       [LITHOLOGICAL RESISTANCE HIERARCHY]\n                                        |\n       +--------------------------------+--------------------------------+\n       |                                |                                |\n       v                                v                                v\n[POROUS SANDSTONE]               [DENSE BASALT]                  [MASSIVE GRANITE]\n• Soluble Calcite Cement         • Thermodynamically Unstable    • Inert Quartz (30%)\n• 25% Porosity Fluid Influx        Augite & Olivine Minerals     • Interlocking Crystalline Mosaic\n• Disaggregates Rapidly          • Columnar Cooling Joints Attack • Impermeable (<1% Porosity)\n       |                                |                                |\n       v                                v                                v\n[FASTEST WEATHERING RATE]       [INTERMEDIATE WEATHERING RATE]   [SLOWEST WEATHERING RATE]\nYields Light Sandy Loams        Yields Fertile Heavy Clays        Yields Coarse Red Soils"
  },

  QB_WTH_05_007: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Under identical macroclimatic regimes, the weathering dynamics of pyroclastic fine-grained Volcanic Ash (tephra, <2 mm) contrast fundamentally with coarse-grained Gravel (>2 mm clasts up to cobbles). This divergence is governed by the principles of specific surface area, amorphous glass reactivity, and mechanical packing thermodynamics.",
    pillar_2_mechanisms_and_kinetics: "1. Amorphous Volcanic Glass vs Crystalline Minerals: Volcanic ash is rich in non-crystalline, amorphous aluminosilicate volcanic glass shards, quenched instantly from erupting magmas. Lacking a rigid crystal lattice, volcanic glass exhibits very high solubility and rapid dissolution kinetics compared to crystalline gravel minerals.\n2. Specific Surface Area Disparity: Fine-grained volcanic ash particles (mean diameter ~20 μm) present specific surface areas of 5–25 m2/g, whereas coarse gravel (mean diameter 20 mm) exhibits surface areas <0.001 m2/g. Ash particles experience instantaneous surface wetting and rapid chemical hydrolysis.\n3. Neo-Mineral Synthesis: Rapid weathering of volcanic ash precipitates short-range order non-crystalline minerals—allophane, imogolite, and ferrihydrite—giving rise to distinctive volcanic ash Andisols with exceptional phosphorus fixation capacity. Gravel weathers sluggishly through outer rind exfoliation and grain boundary disaggregation.",
    pillar_3_comparative_matrix: "| Parameter | Fine-Grained Volcanic Ash | Coarse Bedrock Gravel |\n| :--- | :--- | :--- |\n| **Grain Size & Fabric** | Fine particulate (<2 mm), porous glass shards | Coarse clastic (>2 mm to 64 mm), crystalline |\n| **Mineral Crystallinity** | Amorphous volcanic glass & microlites | Highly crystalline primary silicate minerals |\n| **Specific Surface Area** | Extremely High ($5\\text{--}25 \\text{ m}^2/\\text{g}$) | Extremely Low ($<0.001 \\text{ m}^2/\\text{g}$) |\n| **Dominant Reaction** | Instantaneous congruent glass dissolution | Sluggish rim oxidation and joint hydrolysis |\n| **Weathering Timeframe** | Decades to centuries | Millennia to tens of millennia |\n| **Soil Order Formed** | Andisols (rich in allophane & imogolite) | Inceptisols / Entisols (skeletal, stony phases) |\n| **P-Fixation Capacity** | Extremely High (P-retention >85% by allophane) | Low to moderate (tied to secondary clay rinds) |",
    pillar_4_agronomic_applications: "1. Genesis of High-Yield Andisols: Rapid volcanic ash weathering produces the world's most fertile agricultural soils (e.g., in Indonesia, Japan, East Africa), characterized by low bulk density (<0.9 g/cm3), exceptional water holding capacity, and friable tilth.\n2. Specialized Phosphorus Fertilization: Crops cultivated on weathered ash soils require high banded phosphate fertilizers due to severe P-fixation by allophanic minerals.\n3. Gravel Mulching & Soil Aeration: Unweathered coarse gravel is utilised agronomically as gravel mulches in arid zones to suppress evaporative water loss and prevent wind erosion.",
    pillar_5_diagnostic_synthesis: "                       [IDENTICAL CLIMATIC FORCING]\n                                    |\n         +--------------------------+--------------------------+\n         |                                                     |\n         v                                                     v\n[FINE VOLCANIC ASH]                                  [COARSE GRAVEL]\n• Amorphous Unstable Glass Shards                    • Dense Crystalline Silicate Matrix\n• High Surface Area (15 m2/g)                        • Low Surface Area (0.001 m2/g)\n• Rapid Congruent Dissolution                        • Extremely Sluggish Outer Rind Attack\n         |                                                     |\n         v                                                     v\n[ALLOPHANE & IMOGOLITE SYNTHESIS]                    [SKELETAL GRAVELLY RESIDUE]\nFormation of Highly Fertile Andisols                 Low Moisture Retention Agricultural Soils"
  },

  QB_WTH_05_008: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Diurnal thermal stress weathering (commonly termed insolation weathering or thermoclasty) is the mechanical fracturing and disintegration of exposed rock surfaces caused by cyclical temperature fluctuations. This physical process operates without fluid chemical alteration and is driven by the differential volumetric thermal expansion of polymineralic grains combined with the exceptionally low thermal conductivity of rock fabrics.",
    pillar_2_mechanisms_and_kinetics: "1. Linear & Volumetric Thermal Expansion Differentials: Rocks are aggregates of minerals with differing coefficients of volumetric thermal expansion ($\\alpha_V$). For example, Quartz expands at $\\alpha_V \\approx 36 \\times 10^{-6} \\text{ K}^{-1}$, whereas Plagioclase feldspar expands at $\\alpha_V \\approx 12 \\times 10^{-6} \\text{ K}^{-1}$ and Hornblende at $\\alpha_V \\approx 22 \\times 10^{-6} \\text{ K}^{-1}$. In desert biomes where rock surface temperatures swing from 0°C at night to 60°C under midday sun (ΔT = 60 K), adjacent mineral grains expand at unequal rates, generating shearing stresses along inter-crystalline boundaries.\n2. Low Thermal Conductivity Gradient: Solid rocks have poor thermal conductivity ($k \\approx 1.5\\text{--}3.0 \\text{ W}/(\\text{m}\\cdot\\text{K})$). Solar radiation heats only the outermost 2–5 cm of rock, while the interior remains cold. This steep thermal gradient creates differential expansion stresses between the hot outer shell and cold core.\n3. Fatigue Limit & Microfracture: Repeated diurnal cycling exceeds the rock's tensile fatigue strength (typically 5–15 MPa), initiating sub-critical micro-cracks that coalesce into macro-fractures, culminating in shattering and granular disintegration.",
    pillar_3_comparative_matrix: "| Parameter | Polymineralic Granitic Rock | Monomineralic Quartzite Rock |\n| :--- | :--- | :--- |\n| **Mineralogical Composition** | Quartz, Orthoclase, Plagioclase, Biotite | Monomineralic Quartz (>95% SiO2) |\n| **Expansion Differential** | Extreme; differing $\\alpha_V$ across adjacent grains | Homogeneous $\\alpha_V$ across entire rock matrix |\n| **Dominant Failure Mode** | Granular disintegration (grusification into sand) | Macroscopic thermal jointing & block detachment |\n| **Thermal Gradient Stress**| High both inter-granular and shell-to-core | Concentrated primarily at outer shell-to-core boundary |\n| **Weathering Rate in Deserts**| Rapid; breaks into multi-mineral grus | Slow; retains polished desert varnish for centuries |",
    pillar_4_agronomic_applications: "1. Coarse Desert Soil Parent Material: Insolation weathering produces the coarse, angular sandy soils characteristic of arid agricultural zones (Aridisols), which require drip irrigation to manage low moisture retention.\n2. Agricultural Stone Clearing: In arid fringe farming, rock fragments shattered by diurnal stress break down into manageable pebbles that can be incorporated or cleared for seedbed prep.\n3. Grus-Derived Soil Potassium: Granular disintegration of granite exposes fresh orthoclase feldspar surfaces, accelerating potassium release in semi-arid soils.",
    pillar_5_diagnostic_synthesis: "[INTENSE DIURNAL SOLAR RADIATION (Surface: 60°C)]\n                       |\n                       +---> Low Thermal Conductivity: Interior Remains Cold (20°C)\n                       |     [Severe Thermal Shell-to-Core Stress Gradient]\n                       |\n                       +---> Differential Mineral Expansion:\n                             • Quartz: High Expansion (36x10^-6)\n                             • Feldspar: Low Expansion (12x10^-6)\n                             [Severe Inter-Granular Shear Stresses]\n                       |\n                       v\n[FATIGUE FAILURE EXCEEDS TENSILE STRENGTH (>10 MPa)]\n                       |\n                       v\n[GRANULAR DISINTEGRATION & SURFACE SPALLING (GRUS GENESIS)]"
  },

  QB_WTH_05_009: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Exfoliation—also known as 'onion-skin' weathering, spalling, or sheet jointing—is a physical weathering process wherein curved, concentric concentric rock sheets detach and peel away from massive plutonic or crystalline rock bodies, leaving rounded exfoliation domes and corestones. It is driven by the synergistic coupling of overburden pressure release (sheeting) and diurnal superficial thermal expansion/hydration stresses.",
    pillar_2_mechanisms_and_kinetics: "1. Pressure Release & Unloading (Sheeting Joints): Granites crystallise kilometres beneath the Earth's crust under lithostatic pressures exceeding 100–300 MPa. When geological uplift and erosion strip away kilometres of overlying overburden, the confining pressure drops to ambient atmospheric levels (0.1 MPa). The rock body expands upward and outward.\n2. Formation of Curvature Fracture Planes: Because rock possesses high compressive strength but very low tensile strength (typically <10% of compressive strength), outward expansion produces compressive tensile stresses parallel to the topographic surface, opening curved sub-horizontal fracture sheets.\n3. Thermal & Hydration Spalling: Meteoric moisture enters newly opened curved sheets, hydrating biotite and feldspar minerals. The expansion of hydrating clays within the micro-cracks exerts outward wedging pressure, causing slabs of rock (from a few centimetres to metres thick) to peel off like the layers of an onion.",
    pillar_3_comparative_matrix: "| Parameter | Exfoliation (Sheet Jointing) | Granular Disintegration |\n| :--- | :--- | :--- |\n| **Scale of Detachment** | Massive curved sheets (centimetres to metres thick) | Individual mineral grains (millimetre sand particles) |\n| **Primary Driving Force** | Lithostatic pressure release (elastic decompression) | Inter-mineral differential thermal expansion coefficients |\n| **Rock Fabric Dependency**| Homogeneous, massive, un-jointed plutons (Granite) | Polymineralic rocks with contrasting mineral grain colors |\n| **Resulting Landform** | Exfoliation Domes, Bornhardts, Monadnocks | Grus deposits, pediments, desert gravel plains |\n| **Hydration Role** | Acts as wedge along macroscopic expansion joints | Acts directly on individual biotite/feldspar grain boundaries |",
    pillar_4_agronomic_applications: "1. Hillside Soil Instability: In granitic landscapes (e.g., Telangana, Deccan Plateau, Eastern Ghats), exfoliation sheets on agricultural hillsides peel and slide as rockfalls, posing hazards to terraced agriculture.\n2. Shallow Hillside Soils: Exfoliation domes shed runoff rapidly, preventing deep soil accumulation on upper slopes while depositing colluvial gravelly soils at foot slopes.\n3. Watershed Catchment Management: Impermeable exfoliation domes serve as natural runoff catchments, directing flash runoff into agricultural percolation tanks and farm ponds.",
    pillar_5_diagnostic_synthesis: "[DEEP MAGMATIC PLUTON UNDER HIGH LITHOSTATIC PRESSURE (200 MPa)]\n                             |\n                             v  (Erosion of Overburden Rock Strata)\n[UNLOADING & ELASTIC UPWARD-OUTWARD DECOMPRESSION EXPANSION]\n                             |\n                             v\n[TENSILE STRESS GENERATES CURVED FRACTURE PLANES PARALLEL TO SURFACE]\n                             |\n                             v  (Moisture Infiltration & Thermal Spalling)\n[CONCENTRIC ROCK SHEETS PEEL OFF IN SUCCESSIVE CURVED SLABS]\n                             |\n                             v\n[FORMATION OF ROUNDED EXFOLIATION DOMES & BORNARDTS]"
  },

  QB_WTH_05_010: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "In polymineralic rocks such as granite, diorite, and gneiss, mineral albedo differentials (the ratio of reflected to incident electromagnetic solar radiation) establish localized thermal gradients across adjacent crystal boundaries. This differential thermal absorption drives micro-scale thermal stresses that induce inter-granular micro-fracturing and accelerate rock decay.",
    pillar_2_mechanisms_and_kinetics: "1. Solar Radiation Absorption Thermodynamics: Dark-colored ferromagnesian minerals (e.g., Biotite mica, Hornblende, Augite) have low albedos (absorptivity $\\alpha \\approx 0.85\\text{--}0.95$), absorbing the vast majority of incident solar irradiance. Light-colored minerals (e.g., Quartz, Orthoclase, Plagioclase feldspar) have high albedos (absorptivity $\\alpha \\approx 0.30\\text{--}0.50$), reflecting most solar energy.\n2. Micro-Scale Temperature Gradients: Under direct midday sunlight, adjacent mineral grains separated by fractions of a millimetre experience temperature differences of 5°C to 15°C. Biotite grains can reach 55°C, while contiguous quartz grains remain at 40°C.\n3. Localized Shear Strains: Because thermal expansion is proportional to temperature change ($\\Delta L = L_0 \\cdot \\alpha_L \\cdot \\Delta T$), differential heating induces localized shearing strains along grain boundaries, generating micro-cracks that loosen the interlocking crystalline fabric (grusification).",
    pillar_3_comparative_matrix: "| Mineral Constituent | Albedo / Color | Solar Absorption | Thermal Expansion $\\alpha_V$ | Micro-Stress Behavior |\n| :--- | :--- | :--- | :--- | :--- |\n| **Biotite Mica** | Very Low (Dark Black/Brown)| Very High (>90%) | High, anisotropic cleavage expansion | Expands aggressively; buckles along cleavage |\n| **Hornblende** | Low (Dark Green/Black) | High (~85%) | Moderate ($22 \\times 10^{-6} \\text{ K}^{-1}$) | Generates boundary shear against light silicates |\n| **Quartz** | High (Translucent/White) | Low (~35%) | Very High ($36 \\times 10^{-6} \\text{ K}^{-1}$) | Heated primarily by conduction; high expansion |\n| **Orthoclase Feldspar**| High (Pink / White) | Low (~40%) | Low ($12 \\times 10^{-6} \\text{ K}^{-1}$) | Remains cooler; resists expansion, creating stress |",
    pillar_4_agronomic_applications: "1. Formation of Sandy Grus Soils: Albedo micro-fracturing in granitic terrain drives grusification, forming light, well-drained, sandy loam soils (Alfisols/Red Sandy Soils) widely farmed for groundnut, castor, and millets.\n2. Accelerated Mineral Nutrient Release: By shattering grain boundaries, albedo stress exposes biotite grains to rapid hydrolysis, releasing essential plant nutrients (potassium and magnesium).\n3. Natural Rock Mulch Breakdown: Dark gravel mulches weather faster than light-colored quartz pebbles under intense tropical sunlight, altering soil surface texture over multi-year cycles.",
    pillar_5_diagnostic_synthesis: "                     [SOLAR IRRADIANCE ON POLARIZED MINERAL FABRIC]\n                                           |\n               +---------------------------+---------------------------+\n               |                                                       |\n               v                                                       v\n[DARK MINERALS: BIOTITE / HORNBLENDE]               [LIGHT MINERALS: QUARTZ / FELDSPAR]\n• Low Albedo (High Solar Absorption)                • High Albedo (Reflects Solar Radiation)\n• Rapid Heating: Reaches 55°C+                      • Sluggish Heating: Remains ~40°C\n• High Localized Thermal Expansion                  • Lower Localized Thermal Expansion\n               |                                                       |\n               +---------------------------+---------------------------+\n                                           |\n                                           v\n             [INTER-GRANULAR THERMAL SHEAR STRESSES ALONG GRAIN BOUNDARIES]\n                                           |\n                                           v\n               [MICRO-CRACKING, GRAIN DISAGGREGATION & GRUS SOIL FORMATION]"
  },

  QB_WTH_05_011: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "The transport and abrasive weathering of clastic sediment particles by flowing water are governed by quantitative hydrodynamic velocity thresholds formalized by the Hjulström and Shields entrainment criteria. Water velocity dictates whether sediment fractions undergo deposition, rolling/saltation traction, or suspended transport, directly regulating mechanical bedrock corrasion (abrasion).",
    pillar_2_mechanisms_and_kinetics: "1. Quantitative Hydrodynamic Velocity Thresholds (Hjulström Dynamic):\n   - Silt & Fine Sand (0.02–0.2 mm): Entrained at low velocities (~15–30 cm/s); maintained in suspension at velocities >1 cm/s.\n   - Coarse Sand (0.5–2.0 mm): Requires ~30–50 cm/s for bedload transport.\n   - Gravel & Pebbles (4–64 mm): Requires velocities of 60–150 cm/s for rolling and saltation.\n   - Boulders (>256 mm): Requires torrent velocities >300–500 cm/s for movement.\n   - Clay (<0.002 mm): Requires high entrainment velocity (~100 cm/s) due to electrochemical cohesive bonds, but stays in suspension once mobilized.\n2. Kinetic Energy & Abrasive Wear Law: The kinetic energy of transported clasts is proportional to the square of water velocity ($E_k = \\frac{1}{2} m v^2$), while river bedload transport capacity scales as $v^3$ to $v^6$. Saltating gravel acts as grinding tools (*abraders*), gouging potholes and scouring bedrock channels through mechanical impact and cavitation.",
    pillar_3_comparative_matrix: "| Sediment Fraction | Particle Size Range | Entrainment Velocity Threshold | Dominant Transport Mode | Bedrock Abrasive Wear Potential |\n| :--- | :--- | :--- | :--- | :--- |\n| **Clay & Fine Silt** | $<0.005 \\text{ mm}$ | $\\sim 80\\text{--}100 \\text{ cm/s}$ (Cohesion)| Suspension | Negligible; polishes without impact shatter |\n| **Medium Sand** | $0.25\\text{--}0.50 \\text{ mm}$| $\\sim 20\\text{--}30 \\text{ cm/s}$ | Saltation / Bedload | Moderate; sandpapers and polishes surfaces |\n| **Coarse Gravel** | $16\\text{--}64 \\text{ mm}$ | $\\sim 100\\text{--}150 \\text{ cm/s}$| Traction / Rolling | Very High; mechanical percussion & chipping |\n| **Boulders** | $>256 \\text{ mm}$ | $>300\\text{--}500 \\text{ cm/s}$ (Floods)| Sliding / Saltation | Extreme; shatters bedrock joint blocks |",
    pillar_4_agronomic_applications: "1. Soil Erosion Control & Runoff Management: Agricultural flumes, check dams, and terrace spillways must be designed to keep runoff velocities below critical entrainment thresholds (<30 cm/s) to prevent gully erosion.\n2. Riparian Silt Deposition: Floodwaters dropping below 15 cm/s deposit nutrient-rich silts across agricultural floodplains, naturally rejuvenating alluvial soil fertility (Inceptisols/Entisols).\n3. Canal Siltation Management: Irrigation canals must maintain flow velocities between 60–90 cm/s to prevent sediment deposition without eroding earthen canal banks.",
    pillar_5_diagnostic_synthesis: "[STREAMFLOW VELOCITY DYNAMICS]\n              |\n  +-----------+-------------------------+-------------------------+\n  |                                     |                         |\n  v (V < 15 cm/s)                       v (30 < V < 150 cm/s)     v (V > 300 cm/s: Flood Surge)\n[SEDIMENT DEPOSITION]                 [SALTATION & TRACTION]    [CATASTROPHIC PERCUSSION]\n• Clays & Silts Settle                • Gravel Saltates         • Boulders Crash on Bedrock\n• Floodplain Alluvial Soil Rejuvenated • Scours Bedrock Joints   • Pothole Drilling & Mass Shatter\n• Canal Siltation Risk                • Fluvial Abrasion Engine • Severe Bedrock Comminution"
  },

  QB_WTH_05_012: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Mechanical rock disintegration is vastly more pronounced in high-energy mountainous headwaters than in lowland deltaic reaches. This longitudinal geomorphological disparity is governed by hydraulic energy gradients, gravitational potential energy dissipation, clast-to-clast collision kinetics, and the progressive downstream fining of river sediment.",
    pillar_2_mechanisms_and_kinetics: "1. Longitudinal Stream Profile Energy Dissipation: The stream stream power ($\\Omega = \\rho g Q S$, where $Q$ is discharge and $S$ is hydraulic channel slope) is concentrated in headwaters where channel gradients exceed 5–20% (vs <0.01% in deltaic plains). High energy gradients drive rapid turbulent flow with bed shear stresses exceeding hundreds of Pascals.\n2. Clast Mass & Impact Comminution: Headwater bedload comprises large, angular boulders and cobbles mobilized during monsoonal spates. Clast-on-bedrock collisions generate high impact percussion forces ($F = m \\cdot a = m \\frac{\\Delta v}{\\Delta t}$), chipping bedrock and fracturing boulders along joints. In deltas, the bedload has been ground down to fine sand and suspended silt, which lack the mass to fracture bedrock.\n3. Downstream Fining: As clasts travel downstream, attrition reduces grain diameter through abrasion and hydraulic sorting, diminishing mechanical impact potential.",
    pillar_3_comparative_matrix: "| Morphological Attribute | River Headwaters (Youthful Stage) | Lowland Deltaic Reaches (Old-Age Stage) |\n| :--- | :--- | :--- |\n| **Channel Slope ($S$)** | Steep Gradient ($5\\%\\text{--}20\\%+$) | Minimal Gradient ($<0.01\\%\\text{ to }0.001\\%$) |\n| **Bedload Caliber** | Coarse, angular boulders & cobbles | Fine, rounded quartz sand, silt, and clays |\n| **Hydraulic Flow Regime** | High-energy, macro-turbulent, supercritical | Low-energy, laminar to sub-critical uniform flow |\n| **Dominant Weathering Mode**| Percussion impact fracture, potholing, cavitation | Slow chemical leaching & clay mineral transformation |\n| **Sedimentary Dynamics** | Net vertical erosion and bedrock incising | Net aggradation, sedimentation, and subsidence |\n| **Agricultural Potential** | Fragmentary, rocky terrace soils; high erosion risk| Vast fertile alluvial plains (Indo-Gangetic, Godavari, Krishna) |",
    pillar_4_agronomic_applications: "1. Watershed Soil Protection: Headwater catchments require permanent afforestation and terracing to prevent boulder debris flows from burying downstream agricultural lands.\n2. Deltaic Agricultural Breadbaskets: Lowland deposition of fine-grained sediment over millennia forms the world's most productive agricultural deltas (e.g., Godavari, Krishna, Cauvery deltas), suited for intensive wetland paddy production.\n3. Runoff Energy Dissipation in Farm Drainage: Agricultural drainage engineering applies hydraulic drop structures to mimic the gentle gradients of lowland reaches, preventing gully incising.",
    pillar_5_diagnostic_synthesis: "[HEADWATERS: Steep Slope (10%) + Heavy Angular Boulders]\n                       |\n                       v  (High Kinetic Energy & Percussion Impact)\n[INTENSE MECHANICAL BEDROCK CRUSHING, POTHOLE DRILLING & COMMINUTION]\n                       |\n                       v  (Downstream Attrition & Hydraulic Sorting Over 1000 km)\n[LOWLAND DELTA: Flat Slope (0.01%) + Fine Suspended Silts & Clays]\n                       |\n                       v  (Low Energy Deposition & Chemical Saturation)\n[MINIMAL MECHANICAL DISINTEGRATION; FERTILE ALLUVIAL FLOODPLAIN ACCUMULATION]"
  },

  QB_WTH_05_013: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Cryofracturing—commonly designated frost wedging, gelifraction, or frost shattering—is a physical mechanical weathering process caused by the cyclical freezing and thawing of water confined within rock joints, cleavage fissures, and pore networks. It operates as the dominant mechanical breakdown agent in high-altitude alpine and periglacial environments.",
    pillar_2_mechanisms_and_kinetics: "1. Volumetric Expansion Dynamics: Liquid water undergoes an anomalous structural phase transition upon freezing into hexagonal ice-Ih at 0°C, expanding in volume by **9.05%** (density drops from 1.000 g/cm3 to 0.9167 g/cm3).\n2. Confined Hydrostatic Pressure Generation: If water is enclosed in a closed rock fissure, the freezing front advances from the exterior inward. According to the Clausius-Clapeyron thermodynamic relationship, the crystallization of ice under confined conditions can theoretically generate hydrostatic pressures up to **210 MPa** (2,100 bar) at -22°C.\n3. Tensile Failure of Rock: Massive rock types possess tensile strengths of only 5 to 25 MPa. Because confined frost wedging pressures easily exceed this threshold by up to an order of magnitude, the rock experiences tensile failure, driving crack propagation and shattering rock masses into angular scree and felsenmeer blocks.\n4. Ice Lens Segregation (Frost Heaving): Under sub-zero temperatures, liquid water is drawn through micro-pores toward freezing fronts via cryogenic suction, feeding the growth of segregated ice lenses that wedge fractures open over time.",
    pillar_3_comparative_matrix: "| Parameter | Confined Frost Wedging | Thermal Insolation Shattering |\n| :--- | :--- | :--- |\n| **Phase Transition** | Liquid water to solid hexagonal ice (+9.05% $\\Delta V$)| Zero phase transition; solid-state lattice expansion |\n| **Maximum Stress Exerted**| Up to **210 MPa** in confined fissures | Typically **5–15 MPa** (thermal fatigue) |\n| **Moisture Dependency** | Absolute requirement; inoperative in bone-dry rock | Operates in arid deserts with zero liquid moisture |\n| **Climatic Optimum** | Periglacial alpine zones with frequent 0°C crossings | Hot hyper-arid desert regions with large diurnal $\\Delta T$ |\n| **Debris Morphology** | Highly angular, sharp-edged scree, talus, and felsenmeer| Platy spalls, curved sheets, or rounded grus sand |\n| **Agricultural Hazard** | Destabilizes high-altitude terraces; frost heaves roots | Silt/sand abrasion of tender crop foliage in storms |",
    pillar_4_agronomic_applications: "1. Frost Heaving in Agricultural Seedbeds: In temperate and high-altitude farming, subsoil ice lens formation pushes winter crops (e.g., winter wheat, garlic) out of the ground, severing root systems.\n2. Winter Tillage Clod Disintegration: Farmers in cold agricultural zones utilize frost weathering deliberately by performing coarse autumn ploughing; winter freezing shatters dense clay clods into a fine seedbed tilth without mechanical rolling.\n3. Mountainous Soil Formation: Frost shattering of mountain peaks supplies the parent mineral material that glaciers and alpine rivers transport downstream to form fertile agricultural valleys.",
    pillar_5_diagnostic_synthesis: "[WATER ENTERS OPEN BEDROCK JOINT OR MICRO-FISSURE]\n                       |\n                       v  (Sub-Zero Freezing Event: Water -> Ice Phase Change)\n[9.05% VOLUMETRIC EXPANSION UNDER CONFINED CONDITIONS]\n                       |\n                       v  (Thermodynamic Pressure Generation up to 210 MPa)\n[PRESSURE OVERWHELMS ROCK TENSILE STRENGTH (5-20 MPa)]\n                       |\n                       v\n[CRACK PROPAGATION -> COMPLETE TENSILE SHATTERING OF ROCK]\n                       |\n                       v\n[FORMATION OF ANGULAR TALUS SLOPES, SCREE FIELDS & SEEDBED CRUMB]"
  },

  QB_WTH_05_014: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Glacial bedrock weathering is the suite of mechanical comminution and erosion processes executed by moving alpine glaciers and continental ice sheets. Driven by immense lithostatic ice overburden and basal sliding, it operates through three principal mechanisms: glacial plucking (quarrying), basal abrasion, and subglacial striation and rock-flour formation.",
    pillar_2_mechanisms_and_kinetics: "1. Glacial Plucking (Quarrying): As basal glacier ice flows over bedrock obstacles, overburden pressure increases on the stoss (up-glacier) side, causing basal ice to melt via regelation. As the meltwater flows over to the lee (down-glacier) side, pressure drops and the water refreezes into open bedrock fractures. This frost wedging binds rock blocks into the glacier sole, plucking them away as the ice moves.\n2. Basal Abrasion & Striation Formation: Plucked angular rock clasts and quartz grains embedded in the basal ice act as abrasives. Under immense normal stresses, these tools scour and gouge the underlying bedrock, grinding bedrock surfaces into polished *roches moutonnées* and carving parallel linear grooves (striations) parallel to ice flow.\n3. Rock Flour Generation (Comminution): Continuous subglacial grinding pulverizes rock fragments into silt-sized mineral dust (glacial rock flour, 2–50 μm).",
    pillar_3_comparative_matrix: "| Glacial Mechanism | Physical Process | Driving Force | Morphological Product |\n| :--- | :--- | :--- | :--- |\n| **Glacial Plucking** | Freeze-on detachment of jointed bedrock blocks | Regelation melt-freeze + tractive shear | Asymmetrical steep lee slopes (*Roches Moutonnées*) |\n| **Basal Abrasion** | Sandpapering & scratching of bedrock by embedded clasts| High normal stress + basal sliding velocity | Smooth polished bedrock surfaces & deep striations |\n| **Subglacial Crushing** | Brittle fracture of clasts under heavy ice overburden | Lithostatic ice weight (up to several MPa) | Angular subglacial till, erratics, and moraines |\n| **Rock Flour Synthesis**| Microscopic comminution of primary silicate minerals | Intensive friction between rock particles | Silt-sized rock flour (highly reactive soil parent material) |",
    pillar_4_agronomic_applications: "1. Parent Material of Loess Soils: Wind deflation of glacial outwash plains transports glacial rock flour over thousands of kilometres, depositing extensive loess blankets (e.g., North China Plain, US Midwest, Central Europe) that form some of Earth's most fertile agricultural soils.\n2. Highly Reactive Remineralization Substrate: Because glacial rock flour is physically comminuted without prior chemical leaching, its primary minerals remain unweathered. Applied to depleted tropical soils, rock dust supplies calcium, magnesium, potassium, and trace minerals.\n3. Glacial Till Soil Challenges: Poorly sorted glacial till deposits require extensive rock picking and drainage engineering before agricultural mechanization is feasible.",
    pillar_5_diagnostic_synthesis: "                       [MOVING GLACIER ICE OVERBURDEN]\n                                      |\n         +----------------------------+----------------------------+\n         |                                                         |\n         v (Stoss Side: High Pressure)                             v (Lee Side: Low Pressure Release)\n[BASAL ABRASION & SCRATCHING]                             [REGELATION FREEZE-ON & PLUCKING]\n• Embedded Quartz Grains Act as Cutters                   • Subglacial Meltwater Refreezes in Joints\n• Scours & Polishes Bedrock                               • Blocks Bound to Moving Ice Sheet\n• Pulverizes Bedrock into Reactive Silt                   • Quarries Massive Angular Blocks\n         |                                                         |\n         +----------------------------+----------------------------+\n                                      |\n                                      v\n      [SYNTHESIS OF GLACIAL ROCK FLOUR -> REJUVENATION OF FERTILE LOESS SOILS]"
  },

  QB_WTH_05_015: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Eolian (wind) mechanical weathering and sediment transport operate under the exponential Carrying Power Law (which dictates that wind carrying capacity scales with the sixth power of velocity, $T_c \\propto v^6$) coupled with saltation abrasion. Wind alone cannot break solid rock, but wind armed with saltating quartz sand grains forms a natural sandblasting mechanism that sculpts arid lithologies.",
    pillar_2_mechanisms_and_kinetics: "1. The $v^6$ Carrying Power Law: The mass of the largest particle that can be transported by moving fluids (competence) is proportional to the sixth power of velocity ($W_{\\max} \\propto v^6$). A doubling of wind velocity from 10 m/s to 20 m/s increases carrying power by a factor of $2^6 = 64$, turning a gentle breeze into an abrasive sandstorm.\n2. Saltation Mechanics: Wind-blown sand grains (0.1–0.5 mm) do not float in suspension; they bounce across the desert surface in low ballistic trajectories called saltation. Due to gravity, saltating sand grains rarely bounce higher than **1.0 to 1.5 metres** above the ground, concentrating more than 90% of kinetic energy within a narrow low-altitude zone.\n3. Corrasion & Ventifact Sculpting: The impact of saltating quartz sand grains (Mohs hardness 7) chipping softer rock minerals (feldspar, calcite) scours rock surfaces into polished, faceted stones (ventifacts) and undercuts rock outcrops.",
    pillar_3_comparative_matrix: "| Eolian Transport Mode | Particle Size Range | Transport Altitude | Abrasive Weathering Role |\n| :--- | :--- | :--- | :--- |\n| **Surface Creep / Traction**| Coarse Sand ($0.5\\text{--}2.0 \\text{ mm}$) | Rolling on ground ($0 \\text{ cm}$) | Grinds bedrock surfaces; shapes desert pavements |\n| **Saltation** | Medium Sand ($0.1\\text{--}0.5 \\text{ mm}$) | **0 to 150 cm above ground** | Dominant abrasive tool; sculpts pedestals & yardangs |\n| **Suspension** | Silt & Dust ($<0.05 \\text{ mm}$) | High Altitude ($10\\text{--}3000 \\text{ m}+$) | Negligible abrasion; deposits agricultural loess/dust |",
    pillar_4_agronomic_applications: "1. Crop Sandblasting Injury: In arid farming regions, spring windstorms cause saltating sand to abrade and shred tender crop seedlings (cotton, maize, groundnut) within the 0–50 cm zone, requiring emergency replanting.\n2. Shelterbelt / Windbreak Design: Agricultural shelterbelts (rows of trees planted perpendicular to prevailing winds) reduce surface wind velocity below the critical saltation threshold, protecting topsoil.\n3. Stubble Mulching: Leaving crop residue (stubble) standing in fields increases aerodynamic surface roughness, capturing saltating sand and preventing topsoil deflation.",
    pillar_5_diagnostic_synthesis: "[HIGH VELOCITY ARID WIND FIELD (Velocity Doubles -> Carrying Power Expands 64x)]\n                                      |\n                                      v\n[SALTATION OF QUARTZ SAND GRAINS (Ballistic Bouncing Restricted to 0-1.5m Altitude)]\n                                      |\n                                      v\n[CONCENTRATION OF MAXIMUM KINETIC ENERGY (<1.5m ZONE)]\n                                      |\n                                      v\n[DIFFERENTIAL UNDERCUTTING: PEDESTAL ROCKS, VENTIFACTS & AGRONOMIC CROP SHREDDING]"
  },

  QB_WTH_05_016: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Mushroom Rocks (also known as Pedestal Rocks or *Gour*) and Yardangs are prominent arid eolian erosional landforms created by differential abrasion and wind corrasion. Mushroom rocks are isolated rock pinnacles with narrow bases and bulbous tops, while Yardangs are streamlined, keel-shaped parallel ridges aligned with prevailing unidirectional winds.",
    pillar_2_mechanisms_and_kinetics: "1. Mushroom Rock Genesis (Concentrated Saltation Zone): Eolian abrasion by windblown quartz sand is concentrated within 1.0 to 1.5 metres above the desert floor because gravity limits sand saltation height. While the upper rock mass receives only minor dust impacts, the base is sandblasted. This selective undercutting carves out a narrow supporting stem surmounted by a broad cap.\n2. Lithological Resistance Synergy: Where a massive, resistant caprock (e.g., dense sandstone or basalt) overlies softer, weakly cemented strata (e.g., shale or marl), basal undercutting is further accelerated.\n3. Yardang Genesis (Vortices & Fluting): Yardangs develop in cohesive desert deposits (lacustrine silts, mudstones, or jointed sandstones). Unidirectional winds combined with corkscrew vortex turbulence scour longitudinal troughs along joint weaknesses, streamlining resistant ridges into aerodynamic, ship-hull geometries.",
    pillar_3_comparative_matrix: "| Diagnostic Feature | Mushroom Rocks (Pedestal Rocks) | Yardangs |\n| :--- | :--- | :--- |\n| **Morphological Geometry** | Symmetrical mushroom/pedestal; slender stem, wide cap | Streamlined, elongate, keel-shaped aerodynamic ridges |\n| **Wind Regime Required** | Multi-directional or omnidirectional winds | Strictly unidirectional prevailing winds (trade winds) |\n| **Lithological Structure**| Heterogeneous horizontal strata (hard cap over soft base)| Homogeneous or gently tilted cohesive sedimentary beds |\n| **Dominant Mechanism** | Vertical gradient in saltation abrasion (<1.5 m) | Longitudinal furrow vortex deflation and scouring |\n| **Scale** | Individual isolated features (meters in height) | Field-scale landscape systems (tens to thousands of meters) |",
    pillar_4_agronomic_applications: "1. Indicators of Arid Wind Erosion Severity: The presence of pedestal rocks and yardang fields signals intense eolian activity, identifying lands unsuited for arable cultivation without major windbreak infrastructure.\n2. Micro-Topographic Livestock Shelters: In arid pastoral rangelands, mushroom rocks provide shaded resting micro-habitats for grazing livestock (sheep, goats, camels).\n3. Arid Topsoil Stripping Warning: The processes carving yardangs illustrate what happens to agricultural fields when topsoil is left bare, exposing subsoils to furrowing and desertification.",
    pillar_5_diagnostic_synthesis: "[UNIDIRECTIONAL DESERT WIND ARMED WITH SALTATING SAND]\n                          |\n        +-----------------+-----------------+\n        |                                   |\n        v (Isolated Pinnacle)               v (Cohesive Sediment Plains)\n[SALTATION ABRASION AT BASE (<1.5m)]   [VORTEX FLUTING ALONG JOINTS]\n• Maximum Sand Blasting at Stems       • Scours Longitudinal Troughs\n• Upper Cap Unscathed by Pure Air      • Streamlines Resistant Ribs\n        |                                   |\n        v                                   v\n[NARROW STEM + BULBOUS TOP]            [KEEL-SHAPED PARALLEL RIDGES]\n(Mushroom / Pedestal Rock)             (Aerodynamic Yardangs)"
  },

  QB_WTH_05_017: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Atmospheric electrical discharges (cloud-to-ground lightning strikes) act as an instantaneous physical and thermal weathering mechanism capable of shattering, explosive fracturing, and melting exposed mountain bedrock. The thermal signature of lightning generates diagnostic geological structures known as fulgurites (tubular glasses) and intense shock-wave shatter cones.",
    pillar_2_mechanisms_and_kinetics: "1. Instantaneous Thermal Shock & Plasma Expansion: A typical cloud-to-ground lightning discharge channels peak currents of 30,000 to 100,000 Amperes over tens of microseconds, heating the lightning channel to temperatures exceeding **25,000 to 30,000 K** (hotter than the sun's surface). The sudden heating instantly vaporizes pore water within bedrock fissures.\n2. Explosive Steam Cavitation & Acoustic Shock Wave: The instantaneous explosive phase change of confined moisture from liquid to superheated steam ($>1,600\\times$ volumetric expansion) combined with acoustic shock waves generates localized explosive stresses exceeding hundreds of Megapascals, blasting rock blocks into angular fragments.\n3. Petrological Vitrification (Fulgurite Genesis): Where lightning strikes quartz-rich rocks or sand, the extreme heat melts the rock along discharge channels, vitrifying silica into natural, amorphous lechatelierite glass tubes called petrofulgurites.",
    pillar_3_comparative_matrix: "| Parameter | Lightning Discharge Weathering | Diurnal Thermal Insolation |\n| :--- | :--- | :--- |\n| **Temperature Magnitude** | **25,000 K to 30,000 K** (Plasma arc) | 270 K to 340 K (ambient solar heating) |\n| **Time Duration** | Microseconds ($10^{-5} \\text{ s}$) | 12 hours heating / 12 hours cooling cycles |\n| **Dominant Mechanical Force**| Explosive steam vaporization & acoustic shock | Differential thermal expansion coefficients |\n| **Mineral Transformation**| Melting & vitrification into glass (Fulgurites) | Zero melting; inter-granular micro-crack propagation |\n| **Spatial Distribution** | Highly localized, stochastic (mountain ridges) | Regional, pervasive across entire landscapes |",
    pillar_4_agronomic_applications: "1. Atmospheric Nitrogen Fixation: While lightning mechanically shatters mountain peaks, its electrical arc oxidizes atmospheric nitrogen ($N_2 + O_2 \\rightarrow 2NO \\rightarrow NO_2$), which dissolves in rain to deliver natural nitrate fertilizer ($HNO_3$) directly to crop soils.\n2. Mountain Pasture Disruption: Lightning strikes on exposed rocky rangelands can shatter rocky outcrops into boulder debris that rolls onto lower alpine grazing terraces.\n3. Safety and Infrastructure on Farm Outposts: Lightning poses severe hazards to metal farm infrastructure, elevated irrigation pivots, and hilltop livestock shelters.",
    pillar_5_diagnostic_synthesis: "[CLOUD-TO-GROUND LIGHTNING DISCHARGE (100,000 Amperes)]\n                          |\n                          v\n[INSTANTANEOUS PLASMA ARC HEATING (T > 25,000 K)]\n                          |\n        +-----------------+-----------------+\n        |                                   |\n        v                                   v\n[SUPERHEATED VAPORIZATION OF PORE WATER] [EXTREME THERMAL VITRIFICATION]\n• Explosive Steam Pressure (>500 MPa)    • Quartz Melts into Lechatelierite\n• Acoustic Shock Wave Shivers Rock       • Forms Tubular Petrofulgurites\n        |                                   |\n        +-----------------+-----------------+\n                          |\n                          v\n[CATASTROPHIC PHYSICAL SHATTERING OF EXPOSED MOUNTAIN BEDROCK]"
  },

  QB_WTH_05_018: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Higher plants (vascular tracheophytes, shrubs, and forest trees) execute biological weathering through a coupled biomechanical and biochemical continuum. Plant root systems physically shatter bedrock along joints via root wedging (bioturbation) while simultaneously deploying rhizosphere root exudates, carbonic acid, and mycorrhizal organic acids that chemically decompose primary minerals.",
    pillar_2_mechanisms_and_kinetics: "1. Biomechanical Root Wedging (Turgor Pressure): Roots penetrate microscopic rock fissures seeking moisture. As root diameters expand through secondary growth, cellular turgor generates radial pressures of **1.0 to 2.5 MPa** (10–25 bar). Because massive rocks have low tensile strength, this sustained radial expansion wedges joint blocks apart.\n2. Biochemical Rhizosphere Respiration: Actively respiring roots and mycorrhizae consume carbohydrates, releasing carbon dioxide into rhizosphere pores. This elevates soil pCO2 to 10–100× atmospheric levels, driving carbonic acid formation:\n   $$\\text{CO}_2 + \\text{H}_2\\text{O} \\rightleftharpoons \\text{H}_2\\text{CO}_3 \\rightleftharpoons \\text{H}^+ + \\text{HCO}_3^-$$\n3. Organic Acid Chelation: Roots and associated ectomycorrhizal fungi actively secrete low-molecular-weight organic acids (oxalic, citric, malic, and piscidic acids). These protonate mineral lattices and chelate structural cations (Fe3+, Al3+, Ca2+), stripping them from primary silicate crystals and forming soluble organo-metallic complexes.",
    pillar_3_comparative_matrix: "| Parameter | Biomechanical Plant Action | Biochemical Plant Action |\n| :--- | :--- | :--- |\n| **Operating Tool** | Woody root secondary growth & turgor pressure | Rhizosphere exudates (organic acids, $H^+$, chelators)|\n| **Mechanical / Chemical Action**| Sustained lateral expansion wedging rock joints | Silicate hydrolysis, proton attack, cation chelation |\n| **Spatial Extent** | Confined to macroscopic fracture and bedding planes| Pervasive across entire root-soil contact surface |\n| **Primary Minerals Targeted** | Any rock regardless of mineral composition | High-susceptibility silicates (feldspars, biotite, apatite)|\n| **Agronomic Benefit** | Opens subsoil pathways for deep moisture storage | Solubilizes insoluble P, K, and micro-nutrients |",
    pillar_4_agronomic_applications: "1. Bio-Tillage by Cover Crops: Deep-rooted cover crops (e.g., Daikon radish, Alfalfa) utilize root turgor to shatter compacted subsoil plow-pans ('biological ripping'), restoring soil aeration and drainage.\n2. Nutrient Mining by Perennial Agroforestry: Deep tree roots penetrate weathered saprolite, mining calcium, magnesium, and potassium from deep horizons and recycling them to the surface topsoil via leaf fall.\n3. Green Manure Acidification for Calcareous Soils: Growing green manure crops (e.g., *Crotalaria juncea*, *Sesbania aculeata*) releases organic acids that solubilize native soil phosphorus and micronutrients in high-pH soils.",
    pillar_5_diagnostic_synthesis: "                       [PENETRATION OF ROCK FISSURE BY VASCULAR ROOT]\n                                             |\n         +-----------------------------------+-----------------------------------+\n         |                                                                       |\n         v (Biomechanical Vector)                                                v (Biochemical Vector)\n[SECONDARY MERISTEM DIAMETER GROWTH]                                    [RHIZOSPHERE METABOLISM & EXUDATION]\n• Root Turgor Pressure Exerts 1.5-2.5 MPa                                • Elevated Root Respiration (10-100x pCO2)\n• Exceeds Rock Tensile Joint Resistance                                 • Secretion of Oxalic, Citric, & Malic Acids\n• Wedges Bedrock Apart Mechanically                                     • Chelation of Fe3+, Al3+, & Silicate Hydrolysis\n         |                                                                       |\n         +-----------------------------------+-----------------------------------+\n                                             |\n                                             v\n          [RAPID BIOLOGICAL CONVERSION OF MASSIVE BEDROCK INTO RICH ARABLE SOLUM]"
  },

  QB_WTH_05_019: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "Faunal biological weathering (zoological pedoturbation) is the physical disintegration, chemical transformation, and vertical translocation of rock and soil particles driven by animal activities. It spans a continuum from invertebrate macrofauna (earthworms, termites, ants) to fossorial vertebrates (rodents, burrowing mammals) and anthropogenic disturbances (mechanized excavation, blasting, and intensive agriculture).",
    pillar_2_mechanisms_and_kinetics: "1. Invertebrate Pedoturbation (Earthworms & Termites):\n   - *Earthworms* (*Lumbricus terrestris*, *Eisenia fetida*): Ingest mineral grains along with organic detritus, passing up to 40–100 tonnes of soil/hectare/year through their gizzards. Mechanical grinding with ingested quartz sand particles abrades mineral grains, while digestive gut fluids (neutral pH, abundant calcium humates) precipitate organo-mineral aggregates.\n   - *Termites & Ants*: Excavate deep subterranean galleries penetrating down into saprolite, carrying mineral particles to surface mounds. Termites utilize saliva containing formic and organic acids to cement mounds, modifying mineral weathering rinds.\n2. Vertebrate Bioturbation: Burrowing rodents (moles, ground squirrels) physically excavate rock fragments, churning subsoil into topsoil and opening macro-pores that facilitate rainwater and air ingress into unweathered horizons.\n3. Anthropogenic Disturbance: Human activities act as a planetary weathering engine, moving more sediment and rock annually via mining, blasting, deep ripping, and mechanized tillage than all natural rivers combined.",
    pillar_3_comparative_matrix: "| Agent Category | Representative Organisms | Weathering Mechanism | Agronomic & Soil Impact |\n| :--- | :--- | :--- | :--- |\n| **Invertebrate Macrofauna**| Earthworms, Termites, Ants | Gizzard grinding, burrowing, gut chelation | Forms water-stable granular casts; enhances macropores |\n| **Fossorial Vertebrates** | Rodents, Badgers, Moles | Physical excavation of saprolite & stones | Homogenizes soil profile (bioturbation); aeration |\n| **Anthropogenic Agents** | Humans (Plows, Excavators, Mining) | Explosive shattering, tillage, chemical inputs | Massive comminution, subsoil compaction, accelerated erosion |",
    pillar_4_agronomic_applications: "1. Soil Health Enhancement via Earthworm Casts: Earthworm activity produces water-stable granular aggregates, increases soil porosity by 20–40%, and concentrates available nitrogen, phosphorus, and potassium in surface horizons.\n2. Termite Mound Soil Fertility: Farmers in semi-arid tropical agro-ecosystems actively spread nutrient-rich termite mound soil onto poor sandy fields to boost fertility and clay content.\n3. Conservation Agriculture & Tillage Reduction: Minimizing deep mechanical inversion tillage preserves delicate faunal burrow networks and prevents structural collapse of earthworm bio-pores.",
    pillar_5_diagnostic_synthesis: "                       [FAUNAL INVASION OF THE SOIL & ROCK PROFILE]\n                                             |\n         +-----------------------------------+-----------------------------------+\n         |                                   |                                   |\n         v                                   v                                   v\n[EARTHWORM ACTIVITY]                 [TERMITE / ANT FAUNA]               [ANTHROPOGENIC FORCES]\n• Ingestion & Gizzard Grinding       • Subterranean Mine Shafts           • Mechanized Deep Tillage\n• Enzymatic Gut Modification         • Termite Formic Acid Secretions     • Explosive Blast Fracturing\n• Biogenic Granular Casts Formed     • Heavy Translocation of Saprolite   • Shovel & Heavy Machinery\n         |                                   |                                   |\n         +-----------------------------------+-----------------------------------+\n                                             |\n                                             v\n          [COMPLETE PHYSICAL COMMINUTION & BIOGEOCHEMICAL RESTRUCTURING OF SOIL]"
  },

  QB_WTH_05_020: {
    marking_rubric: rubric,
    pillar_1_nomenclature: "The core mathematical axiom governing physical weathering and chemical reaction kinetics is the inverse proportionality between particle diameter and Specific Surface Area ($SSA$). Physical comminution shatters geometric volumes into smaller fractions, exponentially expanding the reactive interfacial area exposed to chemical attack per unit mass.",
    pillar_2_mechanisms_and_kinetics: "1. Mathematical Derivation for Spherical / Cubic Particles:\n   - Let a cubic mineral block have edge length $L$ and density $\\rho$.\n   - Volume $V = L^3$, Mass $M = \\rho L^3$, Surface Area $A = 6 L^2$.\n   - Specific Surface Area per unit mass ($SSA_M$):\n     $$SSA_M = \\frac{A}{M} = \\frac{6 L^2}{\\rho L^3} = \\frac{6}{\\rho L}$$\n   - Thus, Specific Surface Area is strictly inversely proportional to particle edge length: $SSA \\propto \\frac{1}{L}$.\n2. Quantitative Comminution Demonstration:\n   - Consider a 1 cm3 cubic quartz rock ($L_1 = 1\\text{ cm} = 10^{-2}\\text{ m}$, mass $\\approx 2.65\\text{ g}$):\n     - Initial Surface Area $A_1 = 6 \\times (10^{-2})^2 = 6 \\times 10^{-4}\\text{ m}^2 = 6\\text{ cm}^2$.\n   - If physical weathering shatters this cube into clay-sized particles of edge length $L_2 = 1\\ \\mu\\text{m} = 10^{-6}\\text{ m}$:\n     - Number of new particles $N = \\left(\\frac{L_1}{L_2}\\right)^3 = (10^4)^3 = 10^{12}$ particles.\n     - Total New Surface Area $A_2 = N \\times 6 L_2^2 = 10^{12} \\times 6 \\times (10^{-6})^2 = 6\\text{ m}^2 = 60,000\\text{ cm}^2$.\n   - Comminution expands reactive surface area by a factor of **10,000 (four orders of magnitude)** for the exact same mass.\n3. Chemical Reaction Kinetics Coupling: According to heterogeneous surface reaction kinetics, dissolution velocity is given by:\n   $$\\frac{dM}{dt} = -k \\cdot A \\cdot (C_{\\text{sat}} - C)$$\n   Because $A$ increases $10,000\\times$, the initial dissolution and chemical leaching rates accelerate 10,000-fold.",
    pillar_3_comparative_matrix: "| Particle Domain | Representative Grain Size ($L$) | Particles from $1 \\text{ cm}^3$ Rock ($N$) | Total Surface Area ($A$) | Relative Chemical Dissolution Rate |\n| :--- | :--- | :--- | :--- | :--- |\n| **Single Massive Block** | $1.0 \\text{ cm} = 10,000 \\ \\mu\\text{m}$ | $1$ | $6 \\text{ cm}^2 = 0.0006 \\text{ m}^2$ | $1\\times$ (Baseline / Glacial) |\n| **Coarse Sand Fraction** | $1.0 \\text{ mm} = 1,000 \\ \\mu\\text{m}$ | $1,000$ ($10^3$) | $60 \\text{ cm}^2 = 0.006 \\text{ m}^2$ | $10\\times$ Speedup |\n| **Fine Silt Fraction** | $0.05 \\text{ mm} = 50 \\ \\mu\\text{m}$ | $8,000,000$ ($8\\times 10^6$) | $1,200 \\text{ cm}^2 = 0.12 \\text{ m}^2$| $200\\times$ Speedup |\n| **Clay Colloid Fraction** | $0.001 \\text{ mm} = 1 \\ \\mu\\text{m}$ | $1,000,000,000,000$ ($10^{12}$) | **$60,000 \\text{ cm}^2 = 6.0 \\text{ m}^2$** | **$10,000\\times$ Exponential Speedup** |",
    pillar_4_agronomic_applications: "1. Agrochemical Reactivity of Lime and Gypsum: Ground agricultural limestone (CaCO3) must be finely ground (<100 mesh, ~150 μm) to provide the surface area needed to neutralize subsoil acidity within a single crop season.\n2. Fertilizer Granulation Balance: Conversely, soluble nitrogen and phosphorus fertilizers are deliberately granulated (2–4 mm beads) rather than applied as powders to reduce surface area, slowing dissolution and minimizing leaching.\n3. Soil Texture and Water Holding Capacity: Clay soils hold 4–6× more water and nutrients than coarse sandy soils because their microscopic particle size provides an immense internal surface area (up to 800 m2/g in smectite clays).",
    pillar_5_diagnostic_synthesis: "[MASSIVE 1 cm³ ROCK: Surface Area = 6 cm²]\n                    |\n                    v  (Physical Fracturing: Comminution into 1 μm Clay Particles)\n[1,000,000,000,000 CUBIC PARTICLES: Surface Area = 60,000 cm² (6 m²)]\n                    |\n                    v  (Applies to Dissolution Kinetic Law: dM/dt = -k · A · ΔC)\n[10,000-FOLD EXPONENTIAL EXPANSION IN REACTIVE CONTACT SITES]\n                    |\n                    v\n[INSTANTANEOUS CHEMICAL HYDROLYSIS, ION DISSOLUTION & ARABLE CLAY GENESIS]"
  }
};

function updateFile(filePath) {
  if (!fs.existsSync(filePath)) {
    console.log('Skipping missing file:', filePath);
    return;
  }
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  data.ideology = "Unified Single-Card Tri-Answer Ideology (2M + 5M + 10M)";
  data.mark_distribution = {
    v1_2mark: 20,
    v2_5mark: 20,
    v2_10mark: 20
  };

  let count = 0;
  data.questions.forEach((q) => {
    if (answers10M[q.id]) {
      q.essay_answer_10mark = answers10M[q.id];
      count++;
    }
  });

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Updated ${filePath}: injected ${count} 10-mark essay answers.`);
}

updateFile(ch3JsonPath);
updateFile(ch3PracticeJsonPath);
updateFile(prodCh3Path);
